Capstone project
redwing555/Capstone-Project- pull request #1
Opened 2021-09-09 13:43 UTC by redwing555

This is an astrophysics conference website for the HTML  / CSS and JavaScript Capstone project.

➡️ Contains 2 pages: Homepage and About page 

➡️ The website is mainly mobile-first and responsive for desktop screens.

➡️It is done using the Microverse project specifications and HTML / CSS / Javascript best practices learner during the first module of the program.

➡️  This is the link for the video on Loom presenting my project:  [Loom recording of project presentation](https://www.loom.com/share/0f00df9801b6476f88af35e2e3d5a755 )

📔📔📔📔📔📔   Unfortunately the video on loom is only 5 mins and I didn't have enough time to go into HTML and CSS specifics about the website.  🙏 🙏 🙏 🙏 🙏

2021-09-09 17:18 UTC, DeliceLydia requested changes
# Hi @redwing555, 

Amazing job for real.. I can see the hard work from your project my major highlights for your project are:
- I liked how you explained each and everything you implemented in the video
- And you highlighted challenges you faced and I can see that you overcame them
- Your app is responsive
- PR is professional
- Commits messages are descriptive
Good job!

There are few issues you still need to address but don't mind you are almost there don't give up

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
-  I recommend that in your README when you are adding a link it doesn't look good when the link shows itself you can do something like []() you add link name and then the link itself will appear as a link I hope you get what I mean


### Cheers and Keep Rocking!👏👏👏

Feel free to leave a question, or a comment on the PR thread if something is not clear 100%. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-09 17:18 UTC, DeliceLydia commented on index.html
> +
- [ ] Please follow the given design on [behance](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) as per requirements you are allowed to personalize contents but should follow the design that means colors, layouts, background..
your page
![bc](https://user-images.githubusercontent.com/44745855/132728145-431d5ea1-27a9-422e-b56b-246753d75bf5.png)

original
![lay](https://user-images.githubusercontent.com/44745855/132728373-03205f8d-d6e8-42a2-a3e5-a3eda2d4e98a.png)

2021-09-09 17:18 UTC, DeliceLydia commented on index.html
> +                </div>
- [ ] Add some margin-bottom between the heading and the speaker this is how it looks on the desktop now
![main](https://user-images.githubusercontent.com/44745855/132729052-67b3dedd-4cbc-4773-bf79-c9294fe4240c.png)

2021-09-09 17:18 UTC, DeliceLydia commented on index.html
> +                </article> -->
- [ ] Please remove commented codes to make your codes clean

2021-09-09 17:18 UTC, DeliceLydia commented on index.html
> +
- [ ] On the desktop this link is not centered please work on that
![cent](https://user-images.githubusercontent.com/44745855/132729634-f229e316-3516-4cc7-9471-be38bbed44e4.png)

2021-09-09 17:18 UTC, DeliceLydia commented on about.html
> +    </nav>
- [ ] On the desktop the navbar links are not all fitting on the page check out this image and make necessary changes
![spa](https://user-images.githubusercontent.com/44745855/132730517-b1faebf0-35cd-41c3-9705-e45a55039194.png)

2021-09-09 17:18 UTC, DeliceLydia commented on README.md
> +This project is [MIT](./MIT.md) licensed  and special credit to Cindy Shin (https://www.behance.net/adagio07) for this template under the Creative Commons license (https://creativecommons.org/license
- [ ] You can do something like special credit to [Cindy Shin](https://www.behance.net/adagio07) for this template under the [Creative Commons license](https://creativecommons.org/licenses/by-nc/4.0/) to look more cleaner.

2021-09-10 10:17 UTC, AshakaE approved these changes
### Hi @redwing555  🙋‍♀️, 

# STATUS APPROVED ✔
Thanks for making the required changes
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-10 10:18 UTC, merged